CREATE TABLE PUBLISHER (
  PUBLISHERCODE INT PRIMARY KEY,
  PUBLISHERNAME VARCHAR(50) NOT NULL
);

CREATE TABLE AUTHOR (
  AUTHORID INT PRIMARY KEY,
  AUTHORNAME VARCHAR(50) NOT NULL
);

CREATE TABLE BOOK (
  BOOKID INT PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  PUBLISHERCODE INT NOT NULL,
  NOOFCOPIES INT NOT NULL,
  FOREIGN KEY (PUBLISHERCODE) REFERENCES PUBLISHER(PUBLISHERCODE)
);

CREATE TABLE BOOK_AUTHOR (
  BOOKID INT NOT NULL,
  AUTHORID INT NOT NULL,
  PRIMARY KEY (BOOKID, AUTHORID),
  FOREIGN KEY (BOOKID) REFERENCES BOOK(BOOKID),
  FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(AUTHORID)
);

CREATE TABLE BORROWER (
  CARDNO INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BOOK_LOAN (
  BOOKID INT NOT NULL,
  CARDNO INT NOT NULL,
  DATEOUT DATE NOT NULL,
  DUEDATE DATE NOT NULL,
  STATUS VARCHAR(10) CHECK (STATUS IN ('R', 'T')),
  PRIMARY KEY (BOOKID, CARDNO , DATEOUT),
  FOREIGN KEY (BOOKID) REFERENCES BOOK(BOOKID),
  FOREIGN KEY (CARDNO) REFERENCES BORROWER(CARDNO)
);

INSERT INTO PUBLISHER VALUES
  (1, 'Penguin Books'),
  (2, 'Oxford University Press'),
  (3, 'Random House');

INSERT INTO AUTHOR VALUES
  (1, 'Jane Austen'),
  (2, 'Ernest Hemingway'),
  (3, 'Agatha Christie'),
  (4, 'William Shakespeare'),
  (5, 'J.K. Rowling'),
  (6, 'Stephen King');

INSERT INTO BOOK VALUES
  (1, 'Pride and Prejudice', 1, 5),
  (2, 'The Old Man and the Sea', 2, 3),
  (3, 'Murder on the Orient Express', 3, 4),
  (4, 'Hamlet', 2, 2),
  (5, 'Harry Potter and the Philosopher''s Stone', 1, 10);
  
  
  
  
 SELECT * FROM BORROWER WHERE CARDNO NOT IN (
 SELECT DISTINCT CARDNO FROM BOOKLOAN WHERE STATUS = 'T');
 
 
SELECT BORROWER.CARDNO, BORROWER.NAME, COUNT(*) AS NUM_BOOKS_CHECKED_OUT FROM BORROWER
JOIN BOOKLOAN ON BORROWER.CARDNO = BOOKLOAN.CARDNO WHERE BOOKLOAN.STATUS = 'T'
GROUP BY BORROWER.CARDNO, BORROWER.NAME HAVING COUNT(*) > 5;


CREATE INDEX idx_bookloan_bookid ON BOOKLOAN (BOOKID);


CREATE VIEW BORROWER_BOOKS_OUT AS SELECT B.CARDNO, B.NAME, COUNT(*) AS NUM_BOOKS_OUT FROM BORROWER B
JOIN BOOKLOAN BL ON B.CARDNO = BL.CARDNO WHERE BL.STATUS = 'T' GROUP BY B.CARDNO, B.NAME;

CREATE PROCEDURE Author_Details(@BookID INT)
AS
BEGIN
  SELECT A.AUTHORID, A.AUTHORNAME, BL.STATUS
  FROM AUTHOR A
  JOIN BOOKAUTHOR BA ON A.AUTHORID = BA.AUTHORID
  JOIN BOOKLOAN BL ON BL.BOOKID = BA.BOOKID
  WHERE BA.BOOKID = @BookID;
END

